openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Alumnos
  description: Documentación de la API de Alumnos de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /alumnos:
    get:
      operationId: "api.alumnos.obtener_todos"
      tags:
        - "Alumnos"
      summary: "Colección de dominios custom"
      description: "Obtiene la lista de todos los domain custom Guardados"
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alumno'
    post:
      operationId: "api.alumnos.crear"
      tags:
        - "Alumnos"
      summary: "Alta de un domino de la materia"
      description: "Crea un nuevo domino y lo agrega a la lista de domino custom"
      requestBody:
        required: true
        x-body-name: 'alumno'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se creo el domino correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        400:
          description: "domino duplicado"
    put:
      operationId: "api.alumnos.put"
      tags:
        - "Alumnos"
      summary: "Alta de un alumno de la materia"
      description: "Cambia una ip de un domain custom ya existente"
      requestBody:
        required: true
        x-body-name: 'alumno'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se creo el alumno correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        400:
          description: "Domain duplicado"


  /alumnos/{dominio}:

    get:
      operationId: "api.alumnos.obtener_uno"
      tags:
        - "Alumnos"
      summary: "Dominio"
      description: "Obtiene un dominio"
      parameters:
        - in: path
          name: dominio
          required: true
          schema:
            type: string
          description: El domain a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        404:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    delete:
      operationId: "api.alumnos.borrar"
      tags:
        - "Alumnos"
      summary: "Borrar alumno de la materia"
      description: "Borra un alumno de la materia"
      parameters:
        - in: path
          name: dominio
          required: true
          schema:
            type: string
          description: El domain a borrar
      responses:
        204:
          description: "Operación de lectura exitosa"
        404:
          description: "Domain no encontrado"
  

# Declaración de tipos de datos
components:
  schemas:
    Alumno:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "number"
        custom:
          type: "boolean"
    InputDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    Error:
      type: "object"
      properties:
        mensaje:
          type: "string"
