openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Alumnos
  description: Documentación de la API de Alumnos de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /custom-domain:
    put:
      operationId: "api.custom-domain.put"
      tags:
        - "custom-domain"
      summary: "Alta de un alumno"
      description: "Cambia una ip de un domain custom ya existente"
      requestBody:
        required: true
        x-body-name: 'alumno'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se creo el alumno correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        400:
          description: "Domain duplicado"
    post:
      operationId: "api.custom-domain.crear"
      tags:
        - "custom-domain"
      summary: "Alta de un domino"
      description: "Crea un nuevo domino y lo agrega a la lista de domino custom"
      requestBody:
        required: true
        x-body-name: 'alumno'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputPost'
      responses:
        201:
          description: "Se creo el domino correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        400:
          description: "domino duplicado"

  /domains/{dominio}:

    get:
      operationId: "api.custom-domain.obtener_uno"
      tags:
        - "domains"
      summary: "Dominio"
      description: "Obtiene un dominio"
      parameters:
        - in: path
          name: dominio
          required: true
          schema:
            type: string
          description: El domain a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        404:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /custom-domain/{dominio}:
    delete:
      operationId: "api.custom-domain.borrar"
      tags:
        - "custom-domain"
      summary: "Borrar dominio"
      description: "Borra un dominio"
      parameters:
        - in: path
          name: dominio
          required: true
          schema:
            type: string
          description: El dominio a borrar
      responses:
        204:
          description: "Operación de lectura exitosa"
        404:
          description: "Domain no encontrado"

  /custom-domain/{q}:
    get:
      operationId: "api.custom-domain.obtener_todos"
      tags:
        - "custom-domain"
      summary: "Buscar dominios custom"
      description: "Buscar dominios custom"
      parameters:
        - in: path
          name: q
          required: false
          schema:
            type: string
          description: El texto a buscar
      responses:
        201:
          description: "Se obtienen dominios"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'


# Declaración de tipos de datos
components:
  schemas:
    Alumno:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "number"
        custom:
          type: "boolean"
    InputDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputPost:
      type: "object"
      properties:
        domain: 
          type: "string"
        ip: 
          type: "string"
    Error:
      type: "object"
      properties:
        mensaje:
          type: "string"
